name: Build & publish Note-Pulse builder image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'README.md'
      - '.github/workflows/**'
  schedule:
    - cron: '0 3 * * 1'    # Weekly rebuild for Alpine & Go security patches

env:
  # 🔒 Central place to bump versions
  GO_VERSION: 1.24.2
  SWAG_VER: v1.16.4
  GCI_VER: v1.64.8
  GOIMPORTS_VER: v0.34.0
  IMAGE_NAME: note-pulse-builder

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # 1. Make the owner lowercase
      - name: owner to lowercase
        id: vars
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Use the lowercase owner in the tag list
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:go${{ env.GO_VERSION }}-alpine
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            SWAG_VER=${{ env.SWAG_VER }}
            GCI_VER=${{ env.GCI_VER }}
            GOIMPORTS_VER=${{ env.GOIMPORTS_VER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
